spring:
  kafka:
    bootstrap-servers: localhost:29092,localhost:29093,localhost:29094
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: "ch.ruyalabs.springkafkalab.dto"
        spring.json.value.default.type: "ch.ruyalabs.springkafkalab.dto.PaymentDto"
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  application:
    name: spring-kafka-lab

app:
  kafka:
    topics:
      payment-request: payment-request
    consumer:
      payment-request:
        group-id: payment-request-consumer-group
