spring:
  kafka:
    bootstrap-servers: localhost:29092,localhost:29093,localhost:29094
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: "ch.ruyalabs.springkafkalab.dto"
        spring.json.value.default.type: "ch.ruyalabs.springkafkalab.dto.PaymentDto"
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  application:
    name: spring-kafka-lab


app:
  kafka:
    topics:
      payment-request: payment-request
      payment-response: payment-response
      partitions: 3
      replication-factor: 3
    consumer:
      payment-request:
        group-id: payment-request-consumer-group
        trusted-packages: "ch.ruyalabs.springkafkalab.dto"
        auto-offset-reset: "earliest"
        enable-auto-commit: false
    producer:
      acks: "all"
      retries: 3
      enable-idempotence: true
      transactional-id: "payment-response-producer"
      transaction-timeout-ms: 120000

  simulation:
    balance-check:
      # BUSINESS LOGIC EXCEPTIONS
      simulate-insufficient-balance: false          # Throws: InsufficientBalanceException
      simulate-account-not-found: false             # Throws: AccountNotFoundException

      # INFRASTRUCTURE/TEMPORARY EXCEPTIONS
      simulate-service-unavailable: false            # Throws: ServiceUnavailableException

    payment-execution:
      # BUSINESS LOGIC EXCEPTIONS
      simulate-payment-processing-exception: false  # Throws: PaymentProcessingException
      simulate-invalid-payment-method-exception: false # Throws: InvalidPaymentMethodException

      # INFRASTRUCTURE/TEMPORARY EXCEPTIONS
      simulate-gateway-timeout-exception: false     # Throws: GatewayTimeoutException
