spring:
  kafka:
    bootstrap-servers: localhost:29092,localhost:29093,localhost:29094
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: "ch.ruyalabs.springkafkalab.dto"
        spring.json.value.default.type: "ch.ruyalabs.springkafkalab.dto.PaymentDto"
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  application:
    name: spring-kafka-lab

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    ch.ruyalabs.springkafkalab: INFO
    org.springframework.kafka: WARN
    org.apache.kafka: WARN

app:
  kafka:
    topics:
      payment-request: payment-request
      payment-response: payment-response
      partitions: 3
      replication-factor: 3
    consumer:
      payment-request:
        group-id: payment-request-consumer-group
        trusted-packages: "ch.ruyalabs.springkafkalab.dto"
        auto-offset-reset: "earliest"
        enable-auto-commit: false
    producer:
      acks: "all"
      retries: 3
      enable-idempotence: true
      transactional-id: "payment-response-producer"
    error-handler:
      retry:
        initial-interval: 1000
        multiplier: 2.0
        max-interval: 30000
        max-elapsed-time: 30000
  simulation:
    balance-check:
      simulate-insufficient-balance: false
      simulate-account-not-found: false
      simulate-service-unavailable: false
    payment-execution:
      simulate-payment-processing-exception: false
      simulate-invalid-payment-method-exception: false
      simulate-gateway-timeout-exception: false
