openapi: 3.1.0
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https://api.example.com'
paths: { }
components:
  schemas:
    PaymentDto:
      type: object
      required:
        - paymentId
        - amount
        - currency
        - paymentMethod
        - customerId
      properties:
        paymentId:
          type: string
          description: Unique identifier for the payment
          example: "pay_1234567890abcdef"
          pattern: "^pay_[a-zA-Z0-9]{16}$"
        amount:
          type: number
          format: double
          description: Payment amount in the specified currency
          minimum: 0.01
          maximum: 999999.99
          example: 99.99
        currency:
          type: string
          description: ISO 4217 currency code
          pattern: "^[A-Z]{3}$"
          example: "USD"
        paymentMethod:
          type: string
          description: Method used for payment
          enum:
            - CREDIT_CARD
            - DEBIT_CARD
            - BANK_TRANSFER
            - PAYPAL
            - APPLE_PAY
            - GOOGLE_PAY
          example: "CREDIT_CARD"
        status:
          type: string
          description: Current status of the payment
          enum:
            - PENDING
            - PROCESSING
            - COMPLETED
            - FAILED
            - CANCELLED
            - REFUNDED
          example: "PENDING"
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the payment was created
          example: "2023-12-01T10:30:00Z"
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when the payment was last updated
          example: "2023-12-01T10:35:00Z"
        description:
          type: string
          description: Optional description of the payment
          maxLength: 500
          example: "Payment for order #12345"
        customerId:
          type: string
          description: Identifier of the customer making the payment
          example: "customer_xyz789"
    PaymentResponseDto:
      type: object
      required:
        - status
      properties:
        paymentId:
          type: string
          description: Unique identifier for the payment
          example: "pay_1234567890abcdef"
          pattern: "^pay_[a-zA-Z0-9]{16}$"
        status:
          type: string
          description: Current status of the payment
          enum:
            - PENDING
            - PROCESSING
            - COMPLETED
            - FAILED
            - CANCELLED
            - REFUNDED
            - ERROR
          example: "COMPLETED"
        amount:
          type: number
          format: double
          description: Payment amount in the specified currency
          minimum: 0.01
          maximum: 999999.99
          example: 99.99
        currency:
          type: string
          description: ISO 4217 currency code
          pattern: "^[A-Z]{3}$"
          example: "USD"
        paymentMethod:
          type: string
          description: Method used for payment
          enum:
            - CREDIT_CARD
            - DEBIT_CARD
            - BANK_TRANSFER
            - PAYPAL
            - APPLE_PAY
            - GOOGLE_PAY
          example: "CREDIT_CARD"
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the payment was created
          example: "2023-12-01T10:30:00Z"
        success:
          type: boolean
          description: Indicates whether the payment operation was successful
          example: true
        errorCode:
          type: string
          description: Error code when payment processing fails
          example: "INSUFFICIENT_FUNDS"
        errorMessage:
          type: string
          description: Human-readable error message describing what went wrong
          example: "Payment failed due to insufficient funds in the account"
        errorDetails:
          type: object
          description: Additional error details and context
          properties:
            timestamp:
              type: string
              format: date-time
              description: Timestamp when the error occurred
              example: "2023-12-01T10:35:00Z"
            requestId:
              type: string
              description: Unique identifier for the request that caused the error
              example: "req_1234567890abcdef"
            validationErrors:
              type: array
              description: List of validation errors if applicable
              items:
                type: object
                properties:
                  field:
                    type: string
                    description: Field name that failed validation
                    example: "amount"
                  message:
                    type: string
                    description: Validation error message
                    example: "Amount must be greater than 0"
        retryable:
          type: boolean
          description: Indicates whether the failed operation can be retried
          example: false
