openapi: 3.1.0
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https://api.example.com'
paths: { }
components:
  schemas:
    PaymentDto:
      type: object
      required:
        - paymentId
        - amount
        - currency
        - paymentMethod
        - customerId
      properties:
        paymentId:
          type: string
          description: Unique identifier for the payment
          example: "pay_1234567890abcdef"
          pattern: "^pay_[a-zA-Z0-9]{16}$"
        amount:
          type: number
          format: double
          description: Payment amount in the specified currency
          minimum: 0.01
          maximum: 999999.99
          example: 99.99
        currency:
          type: string
          description: ISO 4217 currency code
          pattern: "^[A-Z]{3}$"
          example: "USD"
        paymentMethod:
          type: string
          description: Method used for payment
          enum:
            - CREDIT_CARD
            - DEBIT_CARD
            - BANK_TRANSFER
            - PAYPAL
            - APPLE_PAY
            - GOOGLE_PAY
          example: "CREDIT_CARD"
        status:
          type: string
          description: Current status of the payment
          enum:
            - PENDING
            - PROCESSING
            - COMPLETED
            - FAILED
            - CANCELLED
            - REFUNDED
          example: "PENDING"
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the payment was created
          example: "2023-12-01T10:30:00Z"
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when the payment was last updated
          example: "2023-12-01T10:35:00Z"
        description:
          type: string
          description: Optional description of the payment
          maxLength: 500
          example: "Payment for order #12345"
        customerId:
          type: string
          description: Identifier of the customer making the payment
          example: "customer_xyz789"
    PaymentResponseDto:
      type: object
      required:
        - paymentId
        - amount
        - currency
        - paymentMethod
        - customerId
        - status
      properties:
        paymentId:
          type: string
          description: Unique identifier for the payment
          example: "pay_1234567890abcdef"
        amount:
          type: number
          format: double
          description: Payment amount in the specified currency
          minimum: 0.01
          example: 99.99
        currency:
          type: string
          description: ISO 4217 currency code
          pattern: "^[A-Z]{3}$"
          example: "USD"
        paymentMethod:
          type: string
          description: Method used for payment
          enum:
            - CREDIT_CARD
            - DEBIT_CARD
            - BANK_TRANSFER
            - PAYPAL
            - APPLE_PAY
            - GOOGLE_PAY
          example: "CREDIT_CARD"
        customerId:
          type: string
          description: Identifier of the customer making the payment
          example: "customer_xyz789"
        status:
          type: string
          description: Payment processing status
          enum:
            - success
            - error
          example: "success"
        errorInfo:
          type: string
          description: Error information when status is error